# Generated by Django 4.2.1 on 2026-05-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=50, verbose_name='Уровень сложности')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность (мин)')),
                ('recommended_age', models.CharField(blank=True, max_length=50, verbose_name='Рекомендуемый возраст')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('material_format', models.CharField(blank=True, choices=[('video', 'Видеоурок'), ('text', 'Текстовый конспект'), ('test', 'Интерактивный тест'), ('presentation', 'Презентация'), ('worksheet', 'Рабочий лист'), ('case', 'Кейс')], max_length=50, verbose_name='Формат материала')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='sites.category', verbose_name='Категория')),
                ('extra_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='sites.materialextrainfo', verbose_name='Дополнительная информация')),
                ('tags', models.ManyToManyField(blank=True, related_name='materials', to='sites.tagpost', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Образовательный материал',
                'verbose_name_plural': 'Образовательные материалы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='sites_mater_time_cr_4a0f34_idx'), models.Index(fields=['slug'], name='sites_mater_slug_770c7e_idx')],
            },
        ),
    ]
