# Generated by Django 4.2.1 on 2026-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('programming', 'Программирование'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('data_science', 'Data Science'), ('web_dev', 'Веб-разработка'), ('mobile_dev', 'Мобильная разработка')], default='programming', max_length=50, verbose_name='Категория')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Образовательный материал',
                'verbose_name_plural': 'Образовательные материалы',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='sites_mater_time_cr_4a0f34_idx'), models.Index(fields=['slug'], name='sites_mater_slug_770c7e_idx'), models.Index(fields=['category'], name='sites_mater_categor_e6d09d_idx')],
            },
        ),
    ]
