# Generated by Django 4.2.1 on 2026-06-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='materialextrainfo',
            name='material_format',
        ),
        migrations.RemoveField(
            model_name='materialextrainfo',
            name='recommended_age',
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='sites.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='materialextrainfo',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Уровень сложности'),
        ),
    ]
